# Generated by Django 5.2.8 on 2025-12-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='poll_id',
            field=models.IntegerField(default=0, verbose_name='投票主題編號'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='建立日期'),
        ),
    ]
